sudo: required
language: node_js

node_js:
    - "8.6.0"

before_install:
    # update apt-gets repository sources
    - sudo apt-get update -qq

    # install blender from official sources.
    # This will most propably install an outdated blender version,
    # but it will resolve all system dependencies blender has to be able to run.
    - sudo apt-get install blender

install:
    - yarn

    # download the blender version you want to test against
    - wget https://builder.blender.org/download/blender-2.79-a950af8e24d-linux-glibc219-x86_64.tar.bz2

    # Extract the archive
    - tar jxf blender-2.79-a950af8e24d-linux-glibc219-x86_64.tar.bz2

    # rename the extracted folder to "blender" for easier reference
    - mv blender-2.79-a950af8e24d-linux-glibc219-x86_64 blender_build

    # remove the archive, we do not need it anymore
    - rm blender-2.79-a950af8e24d-linux-glibc219-x86_64.tar.bz2

    # now create a symlink to the addon within blenders addons directory
    # this is important, because otherwhise blender would not be able to load the addon
    - sudo ln -s ${PWD}/blender/io_three_development ${PWD}/blender_build/2.79/scripts/addons/io_three_development

    - ls -al ${PWD}/blender_build/2.79/scripts/addons/io_three_development

script:
    yarn test -- --blender-path=./blender_build/blender --addons-path='./blender_build/2.79/scripts/addons'
